import type { StylesheetStyle } from "cytoscape";

export const CYTOSCAPE_STYLESHEET: StylesheetStyle[] = [
  {
    selector: "node",
    style: {
      label: "data(label)",
      "font-size": 11,
      color: "#e2e8f0",
      "text-outline-color": "#0f172a",
      "text-outline-width": 2,
    },
  },
  {
    selector: "node:childless",
    style: {
      "text-valign": "bottom",
      "text-halign": "center",
      "text-margin-y": 6,
      "text-wrap": "wrap",
      "text-max-width": "120px",
      "background-color": "data(color)",
      width: 36,
      height: 36,
      shape: "ellipse",
    },
  },
  {
    selector: ":parent",
    style: {
      "text-valign": "top",
      "text-halign": "center",
      "text-margin-y": -8,
      "text-wrap": "wrap",
      "text-max-width": "140px",
      shape: "round-rectangle",
      "background-opacity": 0,
      "background-color": "#64748b",
      "border-width": 2,
      "border-color": "#64748b",
      "border-opacity": 0.6,
      padding: "52px 36px 36px 36px",
      "min-width": "80px",
      "min-height": "80px",
    },
  },
  {
    selector: "node.overflow",
    style: {
      shape: "round-rectangle",
      "background-opacity": 0.08,
      "background-color": "#94a3b8",
      "border-width": 1,
      "border-style": "dashed",
      "border-color": "#94a3b8",
      width: 48,
      height: 28,
      "font-size": 10,
      "text-valign": "center",
      "text-margin-y": 0,
      "text-wrap": "wrap",
      "text-max-width": "100px",
    },
  },
  {
    selector: "node:selected",
    style: {
      "border-width": 3,
      "border-color": "#38bdf8",
      "border-opacity": 1,
    },
  },
  {
    selector: "node:active",
    style: {
      "overlay-opacity": 0.15,
      "overlay-color": "#38bdf8",
    },
  },
  {
    selector: "edge",
    style: {
      width: 2,
      "line-color": "#64748b",
      "target-arrow-color": "#64748b",
      "target-arrow-shape": "triangle",
      "curve-style": "bezier",
      label: "data(label)",
      "font-size": 9,
      color: "#94a3b8",
      "text-outline-color": "#0f172a",
      "text-outline-width": 2,
      "text-rotation": "autorotate",
      "text-margin-y": -8,
    },
  },
  {
    selector: "edge:selected",
    style: {
      "line-color": "#38bdf8",
      "target-arrow-color": "#38bdf8",
      width: 3,
    },
  },
];
